{
  imports = [
    ./cloudflared.nix
    ./caddy.nix
    ./searxng.nix
    ./uptime-kuma.nix
    ./vaultwarden.nix
    ./microbin.nix
    ./ntfy
    ./technitium.nix
    ./glance.nix
    ./gitea.nix
    ./cryptpad.nix
    ./it-tools.nix
    ./immich.nix
    ./chibisafe.nix
    ./minecraft
    ./ollama.nix
    ./bracket.nix
    ./speedtest.nix
    ./zipline.nix
    ./pelican.nix
    ./filebrowser.nix
    ./jellyfin.nix
    ./moodle.nix
    ./convertx.nix
  ];
}
