{
  imports = [
    ./cloudflared.nix
    ./caddy.nix
    ./searxng.nix
    ./vaultwarden.nix
    ./microbin.nix
    ./ntfy
    ./technitium.nix
    ./glance.nix
    ./forgejo
    ./cryptpad.nix
    ./it-tools.nix
    ./immich.nix
    ./minecraft
    ./ollama.nix
    ./bracket.nix
    ./speedtest.nix
    ./zipline.nix
    ./jellyfin.nix
    ./moodle.nix
    ./convertx.nix
    ./umami.nix
    ./postgresql.nix
    ./duckdns.nix
    ./grafana.nix
    ./copyparty.nix
    ./tailscale.nix
    ./vscode.nix
    ./matrix
    ./scrutiny.nix
    ./miniflux.nix
    ./nixflix
    ./changedetection.nix
    ./kavita.nix
    ./linkwarden.nix
    ./wastebin.nix
    ./vikunja.nix
    ./davis.nix
    ./takina.nix
    ./libretranslate.nix
    ./webpages
    ./wakapi.nix
  ];
}
