{
  imports = [
    ./cloudflared.nix
    ./caddy.nix
    ./searxng.nix
    ./uptime-kuma.nix
    ./vaultwarden.nix
    ./microbin.nix
    ./ntfy.nix
    ./technitium.nix
    ./glance.nix
    ./gitea.nix
    ./calibre-web.nix
    ./cryptpad.nix
    ./it-tools.nix
    ./immich.nix
    ./chibisafe.nix
    ./minecraft.nix
    ./2fauth.nix
  ];
}
