{
  imports = [
    ./hyprland
    ./rofi
    ./starship.nix
    ./waybar
    ./wlogout
    ./firefox
    ./hypridle.nix
    ./screenshot.nix
    ./swaync
    ./discord
    ./hyprlock
    ./vscodium.nix
    ./chromium.nix
    ./terminal.nix
    ./media.nix
    ./quickshell
    ./better-control.nix
    ./cheatsheet.nix
    ./screenrec.nix
  ];
}
